// Mapa manual: cuando el tag "Genre" de Jellyfin no es confiable,
// usamos esta lista de artistas conocidos como respaldo.
// Las claves van en minúscula/kebab-case porque así se compara contra el "genre" del request.
// Nota: un mismo artista puede aparecer en más de un género (ej. Carlos Vives en vallenato
// y también podría sonar en un bloque de pop-latino) — no hay problema, son listas independientes.
export const ARTIST_GENRE_MAP: Record<string, string[]> = {
  reggaeton: [
    'Daddy Yankee',
    'Don Omar',
    'Bad Bunny',
    'Plan B',
    'Widinson',
    'Wisin & Yandel',
    'Wisin',
    'Ozuna',
    'Farruko',
    'Feid',
    'Nicky Jam',
    'J Balvin',
    'Chino & Nacho',
    'Tito El Bambino',
    'Alkilados',
    'Arcangel',
    'Zion & Lennox',
    'Myke Towers',
    'Rkm & Ken-y',
    'RKM & Ken-Y',
    'J Alvarez',
    'Tego Calderón',
    'Manuel Turizo',
    'Joey Montana',
    'Justin Quiles',
    'Guaynaa',
    'Reykon',
    'Sech',
    'Ivy Queen',
  ],

  vallenato: [
    'Binomio de Oro de América',
    'Los Diablitos',
    'Los Gigantes del Vallenato',
    'Los Inquietos',
    'Los Inquietos del Vallenato',
    'Los Bufalos',
    'Jorge Celedón',
    'Jorge Celedón, Jimmy Zambrano',
    'Jorge Celedón/ Jimmy Zambrano',
    'Kaleth Morales',
    'Embrujo Vallenato',
    'Yiyo Sarante',
    'Patricia Teheran',
    'Silvestre Dangond',
    'Peter Manjarrés',
    'Omar Geles',
    'Carlos Vives',
  ],

  // Música popular/despecho colombiano
  despecho: [
    'Yeison Jimenez',
    'Jessi Uribe',
    'Pipe Bueno',
    'Darío Gómez',
    'Jhonny Rivera',
    'Alzate',
  ],

  bachata: [
    'Aventura',
    'Romeo Santos',
    'Prince Royce',
    'Monchy & Alexandra',
    'Zacarías Ferreira',
    'Xtreme',
    'Elvis Martinez',
  ],

  salsa: [
    'Frankie Ruiz',
    'Frankie Ruíz',
    'Marc Anthony',
    'Victor Manuelle',
    'Gilberto Santa Rosa',
    'Jerry Rivera',
    'Rey Ruiz',
    'Grupo Niche',
    'Guayacan Orquesta',
    'Gran Combo de Colombia',
    "Oscar D'León",
    'Willie Colón',
  ],

  merengue: [
    'Juan Luis Guerra 4.40',
    'Juan Luis Guerra',
    'Sergio Vargas',
    'Eddy Herrera',
    'Elvis Crespo',
  ],

  'pop-latino': [
    'Chayanne',
    'Alejandro Fernández',
    'Julieta Venegas',
    'Jesse & Joy',
    'Fanny Lu',
    'Ana Gabriel',
    'Marco Antonio Solís',
    'Reik',
    'Camila',
    'Río Roma',
    'Thalía',
    'Selena',
    'Miguel Bosé',
    'La Oreja de Van Gogh',
    'Maluma',
  ],

  // Rancheras + grupero/norteño mexicano
  ranchera: [
    'Vicente Fernández',
    'Joan Sebastian',
    'Alejandro Fernández',
    'Christian Nodal',
    'Banda Los Recoditos',
    'Calibre 50',
    'El Chapo De Sinaloa',
    'Grupo Frontera',
    'Bronco',
    'Los Angeles de Charly',
  ],

  'rock-espanol': [
    'Mana',
    'Maná',
    'Enanitos Verdes',
    'Soda Stereo',
    'Hombres G',
    'Los Prisioneros',
    'Los Abuelos de la Nada',
    'Andrés Calamaro',
    'Jarabe de Palo',
    'Mägo de Oz',
    'Rata Blanca',
    'La Unión',
    'Miranda!',
  ],

  'rock-clasico': [
    'Queen',
    'Bon Jovi',
    'Eagles',
    'Europe',
    'Survivor',
    'Black Sabbath',
    'Kiss',
    'Coldplay',
    'Imagine Dragons',
    'Twenty One Pilots',
    'Earth, Wind & Fire',
  ],

  'pop-ingles': [
    'Michael Jackson',
    'Ed Sheeran',
    'Adele',
    'Bruno Mars',
    'The Weeknd',
    'Harry Styles',
    'George Michael',
    'Christina Perri',
  ],

  electronica: [
    'Avicii',
    'Alan Walker',
    'Martin Garrix',
    'David Guetta',
    'Calvin Harris',
    'Skrillex',
    'Daft Punk',
    'LMFAO',
    'Deorro',
    'Baauer',
    'Dynoro',
  ],

  cumbia: [
    'Los Angeles Azules',
    'La Sonora Dinamita',
    'Los Palmeras',
    'Grupo Marabu',
    'Kaoma',
  ],

  rockola: [
    'Segundo Rosero',
    'Julio Jaramillo',
    'Leo Dan',
    'Sahiro',
    'Sahiro, Saul Proaño',
    'Sahiro, Oswaldo Vásquez',
  ],

  // Categoría propia y extensible para música ecuatoriana; hoy solo tiene un artista
  // pero queda lista para que agregues más cuando quieras (Los Terribles del Vallenato,
  // Don Medardo, etc. si decides moverlos aquí)
  ecuatoriano: [
    'Tierra Canela',
  ],
};